name: shmax

on:
  schedule:
    - cron: '16 */02 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Execute Python script
        # Ciktinin ressources/tur/ klasorune yazilmasi
        run: python3 ressources/tur/shmax.py > ressources/tur/shmax.m3u8

      - name: config
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "shmax-bot"

      - name: commit & push
        run: |
          git add ressources/tur/shmax.m3u8
          git commit -m "Show Max Otomatik Guncelleme" || echo "Degisiklik yok"
          git push origin main
